### ISSUE TITLE
Simple documentation

### ISSUE THREAD

**Issue by peldax** [railt/railt#186]
Hello,

We are currently choosing GraphQL library for our project and railt looks really promising. Its well written and modern, but English documentation is rally missing !

We dont need perfect documentation which covers every single detail, but at least a simple example and few words for each class, so you can easily know what to do, how to use it, and also compare this library with competing ones and choose the right one for you.

Thank you.

**Comment by SerafimArts** [comment]
@peldax hello! There is no documentation not only in English, but also in other languages too =)

This is due to the fact that we have to solve quite a few problems associated with the architecture and processing of components. Some ideas turned out to be very successful, some - very bad and require full rewriting.

These full refining can not allow everything to be described in the documentation, because a ~month later they will be outdated.

Over the past time, it has been possible to do a lot and ready-made successful solutions have already been "fixed" under certain versions (for example: https://github.com/phplrt/phplrt or https://github.com/php-graphql/type-system-contracts).

But the kernel itself is currently unstable, and is not covered by tests. Therefore, I can **not recommend** using this solution in projects yet.

**Comment by peldax** [comment]
Thanks for recommendation, our choice is now definitely much easier, but I can't say I am happy with the result... Good luck and may all the ideas be successful in the future!

**Comment by SerafimArts** [comment]
I suggest looking at webonyx. This is the only stable implementation currently supported by the developer. If everything goes well and they supports GraphQL contracts, then some of the components will become fully compatible (like SDL language compiler, GraphQL Client, Code Generator, etc).
